spring:
  application:
    name: product-service
  zipkin:
    baseUrl: http://127.0.0.1:9411/

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

#Tracing
#spring.zipkin.sender.type: rabbit
spring.sleuth.sampler.probability: 1.0
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE